<a href="https://colab.research.google.com/github/sora-ix9/learning_on_Pytorch/blob/main/1_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensors

https://docs.pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html

In PyTorch, we use tensors to encode the inputs and outputs of a model, as well as the model’s parameters.

Tensors are similar to NumPy’s ndarrays, except that tensors can run on GPUs or other hardware accelerators. In fact, tensors and NumPy arrays can often share the same underlying memory, eliminating the need to copy data (see the section Bridge with NumPy). Tensors are also optimized for automatic differentiation.

In [ ]:
import torch
import numpy as np

# [1. Initializing a Tensor](https://docs.pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html#initializing-a-tensor)

There are various ways to create tensor as the shown below:

1.   Create directly from data
2.   Create from a NumPy array
3.   Create from another tensor
4.   Create with random or constant values



In [ ]:
# 1. Create directly from data
data = [[1, 2],[3, 4]]
X1 = torch.tensor(data)             # The data type is automatically inferred.

# 2. Create from a NumPy array
np_array = np.array(data)
X2 = torch.from_numpy(np_array)   # Vice versa is also possible.

# 3. Create from another tensor
ones_x = torch.ones_like(X1)                    # Retains the properties of X1.
rand_X = torch.rand_like(X1, dtype=torch.float) # Overrides the datatype of X1.

# 4. Create with random or constant values
shape = (2, 3, )
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)


print(f"X1 Tensor ({X1.dtype}):")
print(X1, '\n')

print(f"X2 Tensor ({X2.dtype}):")
print(X2, '\n')

print(f"Ones Tensor ({ones_x.dtype}):")
print(ones_x, '\n')

print(f"Random Tensor ({rand_X.dtype}):")
print(rand_X, '\n')

print(f"rand_tensor ({rand_tensor.dtype}):")
print(rand_tensor, '\n')

print(f"ones_tensor ({ones_tensor.dtype}):")
print(ones_tensor, '\n')

print(f"zeros_tensor ({zeros_tensor.dtype}):")
print(zeros_tensor, '\n')

X1 Tensor (torch.int64):
tensor([[1, 2],
        [3, 4]]) 

X2 Tensor (torch.int64):
tensor([[1, 2],
        [3, 4]]) 

Ones Tensor (torch.int64):
tensor([[1, 1],
        [1, 1]]) 

Random Tensor (torch.float32):
tensor([[0.7559, 0.2697],
        [0.2725, 0.3405]]) 

rand_tensor (torch.float32):
tensor([[0.1360, 0.5928, 0.9291],
        [0.1769, 0.3012, 0.7533]]) 

ones_tensor (torch.float32):
tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

zeros_tensor (torch.float32):
tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



# [2. Attributes of a Tensor](https://docs.pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html#attributes-of-a-tensor)

In [ ]:
rand = torch.rand(3, 4)

print(f"Shape of tensor:", rand.shape)
print(f"Datatype of tensor:", rand.dtype)
print(f"The device where tensor is stored on:", rand.device)

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
The device where tensor is stored on: cpu


# [3. Operations on Tensors](https://docs.pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html#operations-on-tensors)

By default, tensors are created on the CPU. We need to explicitly move tensors to the accelerator using .to method (after checking for accelerator availability). Keep in mind that copying large tensors across devices can be expensive in terms of time and memory!

In [ ]:
if torch.accelerator.is_available():
   cur_device = torch.accelerator.current_accelerator().type
else:
  cur_device = 'cpu'

cudu_X1 = X1.to(cur_device)

print('Current device:', cur_device)
print(f"The device where cudu_X1 is stored on:", cudu_X1.device)

Current device: cuda
The device where cudu_X1 is stored on: cuda:0


Standard numpy-like indexing and slicing:

In [ ]:
tensor = torch.ones(4, 4)

print('tensor =', tensor)
print()
print('First row, tensor[0] =', tensor[0])
print()
print('First column, tensor[:, 0] =', tensor[:, 0])
print()
print('Last column, tensor[:, 0] =', tensor[:, -1])
print()

tensor[:, 1] = 0
print('After chaning the tensor,')
print('tensor =', tensor)

tensor = tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

First row, tensor[0] = tensor([1., 1., 1., 1.])

First column, tensor[:, 0] = tensor([1., 1., 1., 1.])

Last column, tensor[:, 0] = tensor([1., 1., 1., 1.])

After chaning the tensor,
tensor = tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


Joining tensors (See also [torch.stack](https://pytorch.org/docs/stable/generated/torch.stack.html) for subtle different joining)

In [ ]:
concate_tensor = torch.cat([tensor, tensor, tensor], dim=1)

concate_tensor

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])

Arithmetic operations

In [ ]:
# Matrix transpose
transpose_tensor = tensor.T

# Matrix multiplication
y1 = tensor @ tensor.T # using @ operator
y2 = tensor.matmul(tensor.T) # using the tensor_obj.matmul() method
y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)  # using the torch.matmul() function and the optinal 'out' argument to store the function output into the variable specified to the argument.

print('tensor =', tensor)
print()
print('transpose_tensor =', transpose_tensor)
print()
print('y1 =', y1)
print()
print('y2 =', y2)
print()
print('y3 =', y3)
print()

tensor = tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

transpose_tensor = tensor([[1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

y1 = tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

y2 = tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

y3 = tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])



In [ ]:
# Element-wise product
z1 = tensor * tensor # using * operator
z2 = tensor.mul(tensor) # using the tensor_obj.mul() method
z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3) # using the torch.mul() function and the optinal 'out' argument to store the function output into the variable specified to the argument.

print('tensor =', tensor)
print()
print('z1 =', z1)
print()
print('z2 =', z2)
print()
print('z3 =', z3)
print()

tensor = tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

z1 = tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

z2 = tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

z3 = tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])



Single-element tensors

In [ ]:
agg_tensor = tensor.sum()
agg_item = agg_tensor.item()

print(f'agg_tensor={agg_tensor}, agg_tensor.dtype={agg_tensor.dtype}')
print()
print(f'agg_item={agg_item}, type(agg_item)={type(agg_item)}')

agg_tensor=12.0, agg_tensor.dtype=torch.float32

agg_item=12.0, type(agg_item)=<class 'float'>


In-place operations: it store the result into the operand are called in-place. They are denoted by an _ suffix. For example:
,

*   x.copy_(y)
*   x.t_() (i.e., it will change x)



In [ ]:
print('tensor =', tensor)
print()

tensor.add_(5)
print('After in-place operations performed:')
print('tensor =', tensor)

tensor = tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

After in-place operations performed:
tensor = tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


Note: In-place operations save some memory, but can be problematic when computing derivatives because of an immediate loss of history. Hence, their use is discouraged.

Ref links for further learning:

* https://pytorch.org/docs/stable/torch.html

# [4. Bridge with NumPy](https://docs.pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html#bridge-with-numpy)

A change in the tensor reflects in the NumPy array.

In [ ]:
ones_tensor = torch.ones(5)
arr = ones_tensor.numpy()

print('ones_tensor =', ones_tensor)
print()
print('arr =', arr)
print()

ones_tensor.add_(1)

print('After in-place operations performed to the ones_tensor:')
print()
print('ones_tensor =', ones_tensor)
print()
print('arr =', arr)

ones_tensor = tensor([1., 1., 1., 1., 1.])

arr = [1. 1. 1. 1. 1.]

After in-place operations performed to the ones_tensor:

ones_tensor = tensor([2., 2., 2., 2., 2.])

arr = [2. 2. 2. 2. 2.]


# [5. NumPy array to Tensor](https://docs.pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html#numpy-array-to-tensor)

Changes in the NumPy array reflects in the tensor.

In [ ]:
ones_arr = np.ones(5)
t = torch.from_numpy(ones_arr)

print('ones_arr =', ones_arr)
print()
print('t =', t)
print()

np.add(ones_arr, 1, out=ones_arr)

print('After in-place operations performed to the ones_arr:')
print()
print('ones_arr =', ones_arr)
print()
print('t =', t)

ones_arr = [1. 1. 1. 1. 1.]

t = tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

After in-place operations performed to the ones_arr:

ones_arr = [2. 2. 2. 2. 2.]

t = tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
